apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kaffee-shops
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Project for Coffee-Shops
  sourceRepos:
    - https://github.com/bwiengarn/kaffee-shop-gitops
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true