# App of Apps: diese eine Application erzeugt alle Kinder aus argocd/apps/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nordlicht-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<DEIN-ACCOUNT>/kaffee-shop-gitops.git
    targetRevision: main
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
