apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop-hooks
resources:
  - ../apps/shop/base
  - 00-namespace-wave.yaml
  - presync-db-migration.yaml
  - postsync-smoketest.yaml
  - syncfail-alert.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: remove
        path: /spec/ports/0/nodePort
    target:
      kind: Service
      name: kaffee-shop
