# App of Apps: diese eine Application erzeugt alle Kinder aus argocd/apps/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kaffee-root
  namespace: argocd
spec:
  project: default
  source:
    - repoURL: https://github.com/bwiengarn/kaffee-shop-gitops.git
      targetRevision: master
      path: demo/tenants/melita
    - repoURL: https://github.com/bwiengarn/kaffee-shop-gitops.git
      targetRevision: master
      path: demo/tenants/tschibo
    - repoURL: https://github.com/bwiengarn/kaffee-shop-gitops.git
      targetRevision: master
      path: demo/tenants/nordlicht
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
